apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lglje96jz-python
  janus-idp.io/tekton: lglje96jz-python
  backstage.io/kubernetes-id: lglje96jz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lglje96jz-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
