apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lglje96jz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lglje96jz-python 
  name: lglje96jz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lglje96jz-python 
